name: Build project

on: [push, pull_request]

jobs:
  buildSimulator:
    name: Build application
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install blender
        run: sudo snap install blender --classic
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs install; git lfs pull
      - name: Cache library files from previous builds
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-StandaloneLinux
          restore-keys: Library-
      - name: Build the project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneLinux64
      - name: Get current time for tag
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+01:00"
      - name: Change name of built directory and files to AscendSimulator
        run: mkdir ${{ steps.current-time.outputs.formattedTime }}${{steps.current-time.outputs.minute}}; 
              sudo mv ./build/StandaloneLinux64/* ${{ steps.current-time.outputs.formattedTime }}${{steps.current-time.outputs.minute}};
              sudo mv ${{ steps.current-time.outputs.formattedTime }}${{steps.current-time.outputs.minute}}/StandaloneLinux64_Data/ ${{ steps.current-time.outputs.formattedTime }}${{steps.current-time.outputs.minute}}/AscendSimulator_Data; 
              sudo mv ${{ steps.current-time.outputs.formattedTime }}${{steps.current-time.outputs.minute}}/StandaloneLinux64/ ${{ steps.current-time.outputs.formattedTime }}${{steps.current-time.outputs.minute}}/AscendSimulator; 
              sudo rm ${{ steps.current-time.outputs.formattedTime }}${{steps.current-time.outputs.minute}}/StandaloneLinux64_BurstDebugInformation_DoNotShip/ -r
      - name: Upload built artefacts
        uses: actions/upload-artifact@v2
        with:
          name: Build-StandaloneLinux64
          path: ${{ steps.current-time.outputs.formattedTime }}${{steps.current-time.outputs.minute}}
      - name: Zip artifact for deployment
        run: zip autobuild${{ steps.current-time.outputs.formattedTime }}${{steps.current-time.outputs.minute}}.zip ./${{ steps.current-time.outputs.formattedTime }}${{steps.current-time.outputs.minute}}/* -r
      - name: Create latest release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.current-time.outputs.formattedTime }}${{steps.current-time.outputs.minute}}"
          artifacts: "autobuild${{ steps.current-time.outputs.formattedTime }}${{steps.current-time.outputs.minute}}.zip"
