name: Build project

on: [push, pull_request]

jobs:
  buildSimulator:
    name: Build application
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install blender
        run: sudo snap install blender --classic
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v3
      - name: Install Git LFS
        run: git lfs install
      - name: Pull the lfs objects
        run: git lfs pull
      - name: Cache library files from previous builds
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-StandaloneLinux
          restore-keys: Library-
      - name: Build the project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneLinux64
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
      - name: Get current time for tag
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+01:00"
      - name: Change name of built directory and files to AscendSimulator
        run: mkdir ${{ env.release_tag }}; 
              sudo mv ./build/StandaloneLinux64/* ${{ env.release_tag }};
              sudo mv ${{ env.release_tag }}/StandaloneLinux64_Data/ ${{ env.release_tag }}/AscendSimulator_Data; 
              sudo mv ${{ env.release_tag }}/StandaloneLinux64 ${{ env.release_tag }}/AscendSimulator; 
              sudo rm ${{ env.release_tag }}/StandaloneLinux64_BurstDebugInformation_DoNotShip/ -r
      - name: Upload built artefacts
        uses: actions/upload-artifact@v2
        with:
          name: Build-StandaloneLinux64
          path: ${{ env.release_tag }}
      - name: Zip artifact for deployment
        run: zip autobuild${{ env.release_tag }}.zip ./${{ env.release_tag }}/* -r
      - name: Create latest release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ env.release_tag }}"
          artifacts: "autobuild${{ env.release_tag }}.zip"

